### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by elad661** [Swatinem/tern_for_gedit#5]
Hi there.

I want to reuse some of your work here to make a JS auto-completion plugin for gnome-builder, but you have not specified a license for your code.

Not providing a license with your code at all means nobody but you can use it, as all rights are reserved to the author by default and there is no license granting rights to anyone else.

Thanks.

**Comment by Swatinem** [comment]
Thanks for reminding me. I added it to the README. I hope that is enough, if not, I can also commit a separate LICENSE file.

For the license itself, it’s now LGPL-3.0 as I do not believe in permissive licenses but rather prefer strong copyleft. :-)
